// <auto-generated />
using CodeFirst.Vehicle.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirst.Vehicle.DataAccessLayer.Migrations
{
    [DbContext(typeof(VehicleDBContext))]
    [Migration("20250506105657_Vehicle")]
    partial class Vehicle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirst.Vehicle.DataAccessLayer.Models.VehicleCategory", b =>
                {
                    b.Property<byte>("CategoryId")
                        .HasColumnType("tinyint");

                    b.Property<string>("CategoryDesciption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("VehicleCategories");
                });

            modelBuilder.Entity("CodeFirst.Vehicle.DataAccessLayer.Models.VehicleProduct", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("CategoryId")
                        .HasColumnType("tinyint");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("VehicleCategoryCategoryId")
                        .HasColumnType("tinyint");

                    b.HasKey("ProductId");

                    b.HasIndex("VehicleCategoryCategoryId");

                    b.ToTable("VehicleProducts");
                });

            modelBuilder.Entity("CodeFirst.Vehicle.DataAccessLayer.Models.VehicleProduct", b =>
                {
                    b.HasOne("CodeFirst.Vehicle.DataAccessLayer.Models.VehicleCategory", "VehicleCategory")
                        .WithMany("VehicleProducts")
                        .HasForeignKey("VehicleCategoryCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleCategory");
                });

            modelBuilder.Entity("CodeFirst.Vehicle.DataAccessLayer.Models.VehicleCategory", b =>
                {
                    b.Navigation("VehicleProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
